---
all:
  children:
    cisco_routers:
      hosts:
        R1-CISCO:
          ansible_host: 192.168.100.1
          ospf_router_id: 1.1.1.1
          mgmt_ip: 192.168.100.1
          ospf_interfaces:
            - { name: GigabitEthernet0/0, area: 0 }
            - { name: GigabitEthernet2/0, area: 0 }
          ospf_networks:
            - { address: 10.0.12.0, wildcard: 0.0.0.3, area: 0 }
            - { address: 10.0.13.0, wildcard: 0.0.0.3, area: 0 }
          interfaces_config:
            - name: GigabitEthernet0/0
              description: "Link_to_R2-CISCO_10.0.12.0/30"
              ipv4: { address: 10.0.12.1, mask: 255.255.255.252 }
            - name: GigabitEthernet2/0
              description: "Link_to_R3-CISCO_10.0.13.0/30"
              ipv4: { address: 10.0.13.1, mask: 255.255.255.252 }
            - name: GigabitEthernet1/0
              description: "Management"
              ipv4: { address: 192.168.100.1, mask: 255.255.255.0 }

        R2-CISCO:
          ansible_host: 192.168.100.2
          ospf_router_id: 2.2.2.2
          mgmt_ip: 192.168.100.2
          ospf_interfaces:
            - { name: GigabitEthernet0/0, area: 0 }
            - { name: GigabitEthernet2/0, area: 0 }
          ospf_networks:
            - { address: 10.0.12.0, wildcard: 0.0.0.3, area: 0 }
            - { address: 10.0.23.0, wildcard: 0.0.0.3, area: 0 }
          interfaces_config:
            - name: GigabitEthernet0/0
              description: "Link_to_R1-CISCO_10.0.12.0/30"
              ipv4: { address: 10.0.12.2, mask: 255.255.255.252 }
            - name: GigabitEthernet2/0
              description: "Link_to_R3-CISCO_10.0.23.0/30"
              ipv4: { address: 10.0.23.1, mask: 255.255.255.252 }
            - name: GigabitEthernet1/0
              description: "Management"
              ipv4: { address: 192.168.100.2, mask: 255.255.255.0 }

        R3-CISCO:
          ansible_host: 192.168.100.3
          ospf_router_id: 3.3.3.3
          mgmt_ip: 192.168.100.3
          mgmt_interface: GigabitEthernet3/0   # override — R3 usa Gi3/0 para gestion
          ospf_interfaces:
            - { name: GigabitEthernet0/0, area: 0  }
            - { name: GigabitEthernet4/0, area: 0  }
            - { name: GigabitEthernet1/0, area: 10 }
            - { name: GigabitEthernet2/0, area: 20 }
          ospf_networks:
            - { address: 10.0.13.0, wildcard: 0.0.0.3, area: 0  }
            - { address: 10.0.23.0, wildcard: 0.0.0.3, area: 0  }
            - { address: 10.0.34.0, wildcard: 0.0.0.3, area: 10 }
            - { address: 10.0.36.0, wildcard: 0.0.0.3, area: 20 }
          interfaces_config:
            - name: GigabitEthernet0/0
              description: "Link_to_R1-CISCO_10.0.13.0/30"
              ipv4: { address: 10.0.13.2, mask: 255.255.255.252 }
            - name: GigabitEthernet4/0
              description: "Link_to_R2-CISCO_10.0.23.0/30"
              ipv4: { address: 10.0.23.2, mask: 255.255.255.252 }
            - name: GigabitEthernet1/0
              description: "Link_to_R4-CISCO_10.0.34.0/30"
              ipv4: { address: 10.0.34.1, mask: 255.255.255.252 }
            - name: GigabitEthernet2/0
              description: "Link_to_R6-CISCO_10.0.36.0/30"
              ipv4: { address: 10.0.36.1, mask: 255.255.255.252 }
            - name: GigabitEthernet3/0
              description: "Management"
              ipv4: { address: 192.168.100.3, mask: 255.255.255.0 }

        R4-CISCO:
          ansible_host: 192.168.100.4
          ospf_router_id: 4.4.4.4
          mgmt_ip: 192.168.100.4
          ospf_interfaces:
            - { name: GigabitEthernet0/0, area: 10 }
            - { name: GigabitEthernet2/0, area: 10 }
          ospf_networks:
            - { address: 10.0.34.0, wildcard: 0.0.0.3, area: 10 }
            - { address: 10.0.45.0, wildcard: 0.0.0.3, area: 10 }
          interfaces_config:
            - name: GigabitEthernet0/0
              description: "Link_to_R3-CISCO_10.0.34.0/30"
              ipv4: { address: 10.0.34.2, mask: 255.255.255.252 }
            - name: GigabitEthernet2/0
              description: "Link_to_R5-CISCO_10.0.45.0/30"
              ipv4: { address: 10.0.45.1, mask: 255.255.255.252 }
            - name: GigabitEthernet1/0
              description: "Management"
              ipv4: { address: 192.168.100.4, mask: 255.255.255.0 }

        R5-CISCO:
          ansible_host: 192.168.100.5
          ospf_router_id: 5.5.5.5
          mgmt_ip: 192.168.100.5
          ospf_interfaces:
            - { name: GigabitEthernet0/0, area: 10 }
            - { name: GigabitEthernet2/0, area: 20 }
          ospf_networks:
            - { address: 10.0.45.0, wildcard: 0.0.0.3, area: 10 }
            - { address: 10.0.56.0, wildcard: 0.0.0.3, area: 20 }
          interfaces_config:
            - name: GigabitEthernet0/0
              description: "Link_to_R4-CISCO_10.0.45.0/30"
              ipv4: { address: 10.0.45.2, mask: 255.255.255.252 }
            - name: GigabitEthernet2/0
              description: "Link_to_R6-CISCO_10.0.56.0/30"
              ipv4: { address: 10.0.56.1, mask: 255.255.255.252 }
            - name: GigabitEthernet1/0
              description: "Management"
              ipv4: { address: 192.168.100.5, mask: 255.255.255.0 }

        R6-CISCO:
          ansible_host: 192.168.100.6
          ospf_router_id: 6.6.6.6
          mgmt_ip: 192.168.100.6
          ospf_interfaces:
            - { name: GigabitEthernet0/0, area: 20 }
            - { name: GigabitEthernet2/0, area: 20 }
          ospf_networks:
            - { address: 10.0.36.0, wildcard: 0.0.0.3, area: 20 }
            - { address: 10.0.56.0, wildcard: 0.0.0.3, area: 20 }
          interfaces_config:
            - name: GigabitEthernet0/0
              description: "Link_to_R3-CISCO_10.0.36.0/30"
              ipv4: { address: 10.0.36.2, mask: 255.255.255.252 }
            - name: GigabitEthernet2/0
              description: "Link_to_R5-CISCO_10.0.56.0/30"
              ipv4: { address: 10.0.56.2, mask: 255.255.255.252 }
            - name: GigabitEthernet1/0
              description: "Management"
              ipv4: { address: 192.168.100.6, mask: 255.255.255.0 }
